### PR TITLE
Fix mn tests

### PR DESCRIPTION
**Pull request by tobiasleibner**

### CODE REVIEW

**Comment by renemilk** [comment]
Master started failing _after_ I merged #133 for some reason: https://travis-ci.org/dune-community/dune-gdt/jobs/425633953
https://travis-ci.org/dune-community/dune-gdt/jobs/425633956
Does this PR maybe address that too?

**Comment by tobiasleibner** [comment]
Not yet, but I will look into it.

**Comment by tobiasleibner** [comment]
@renemilk, could you take a look at https://travis-ci.org/dune-community/dune-gdt/jobs/439366323? Seems like https://github.com/dune-community/dune-gdt/commit/bd796abcf32ba78374f34b38a79efcf5342d8eeb lowered the tolerance but in this branch the errors match the old tolerances.

**Comment by renemilk** [comment]
Uhm, you got that commit into this branch because you rebased on master recently? You could try to revert that commit, but then the PR build should fail...
I'm somewhat clueless atm.

**Comment by tobiasleibner** [comment]
@renemilk, Travis semms to be green now after reverting the tolerance change. Do you want to check why the error went back to its old state or can I just merge this?
I still have the drone.io builds in this PR as I pulled the drone.io branch some time ago. However, all changes from the drone.io branch are now gone from this PR. Can we just ignore the failing drone.io builds or should I merge the drone.io branch again?

**Comment by tobiasleibner** [comment]
C++ tests are green, but the Python tests are failing, apparently due to some permission errors.

**Comment by renemilk** [comment]
@tobiasleibner I've restarted the relevant builds with the new docker base image in hopes to fix the python tests. You probably want to pull in master again tho anyhow.

**Pull request merged**
