### PR TITLE
momentmodels, finite volume with reconstruction

### PR DESCRIPTION
**Pull request by tobiasleibner**
This PR adapts the moment model stuff to the new interfaces. We also need to adapt the numerical flux interface, see https://github.com/dune-community/dune-xt-functions/issues/77. I didn't change the NumericalFluxInterface yet, but I will in updating this PR.

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Changing the numerical-flux interface is done separately in #161.

**Comment by tobiasleibner** [comment]
This pull requests adds back the code for finite volume with slope reconstruction and code to solve moment approximations to kinetic equations. In addition, this adds back some of the timesteppers (in tools/timesteppers/). I was not sure where to put the momentmodel stuff, suggestions are welcome.

To improve performance, I made two interface changes:
1. I changed the apply methods of the local operator interfaces not to take a source. The local operators now have to store the source in the constructors. This improves performance by avoiding calling ``source.local_function()`` on each entity, now the local funtcion can be created in the constructor and only ``bind`` has to be called on each entity. Especially for ``DiscreteFunction``, which allocate some large arrays in the local function constructor, the calls to ``local_function`` were very expensive.
2. The second change is probably more controversial, and I am open to alternative suggestions. Currently, the ``SourceType`` of the local operators is a ``ConstDiscreteFunction``. I renamed that one to ``DiscreteSourceType`` and changed the ``SourceType`` to ``XT::Functions::GridFunctionInterface``. As the ``ConstDiscreteFunction`` is derived from ``GridFunctionInterface``, everything can be used as before, until now nothing used the additional capabilities of ``ConstDiscreteFunction`` for the source. I made this change because for finite volume methods with reconstruction, a ``DiscreteFunction`` is not always the right source type. For polynomial reconstruction, a DG space might be the right solution, but it is much less performant than a simple grid function returning the correct values at the interfaces, if only values at the interface centers are needed. And in the future, I probably want to try some kind of non-linear reconstruction without a suitable space type. 

Other relevant changes to existing files:
- The default_interpolation now uses several threads (we probably want to add an option for that, as basis evaluations for  spaces other than finite volume are not thread-safe at the moment)
- The local operator now has a ``with source`` method to still be able to implement the automatic jacobians

You don’t have to review the files I added back (e.g. all files in the momentmodels/ and tools/timestepper/ folders), just the relevant changes to the preexisting files. And take your time, I am not in hurry to merge this.

**Comment by ftalbrecht** [comment]
Thx for the work! I will look into this in the following days and just start to collect some thoughts here. No need to think about them until I have finished them... :)

* some of that code is still in the old style, as in: the timestepper has a single template argument (the discrete function). In the long run, this should be moved towards the new style of having grid, dimension and vector as template arguments, which will allow us to use one timestepper for different spaces and so on. Very low priority and nothing for this pr

* the changes to the local operator interface are quite interesting. fixing the source makes kind of sense, given our bind() philosophy. On the other hand it was also nice to be able to apply the same op to different sources and the `with_` seems a bit clumsy for that. But in general the new approach looks like the way to go, will think about if we should support the old apply signatures somehow

* having the source a grid function instead of a discrete function is also interesting. The discrete function was used, btw, in the old FV operators, where I directly accessed the DoFs instead of evaluating the function. Other than that I agree that the gridfunction is the correct thing to do. Perhaps we have to support two kinds of operators, a `LocalOperator`, which takes a grid function as source, and a `LocalDiscreteOperator`, which only takes a discrete function an derives from `LocalOperator`. The same problem arises in localizableoperator and localizable functional. there we should also have two variants, one acting on gridfunctions, one on discretefunctions (this has been on my list for quite some time), to easily allow for products of analytical functions for instance. We could than also call these `LocalizableOperatorBase` and `LocalizableDiscreteOperatorBase` or something like that

* from a first glance the momentmodel stuff belongs to the `test/`s. apart from the eulertools, all PDE specific stuff lives in a corresponding folder within `test`

**Comment by ftalbrecht** [comment]
Most likely, I will not look at this until I am back end of May.

**Comment by tobiasleibner** [comment]
Closing this in favor of #170.

**Pull request closed without merging**
