### PR TITLE
CI setup with drone.io

### PR DESCRIPTION
**Pull request by renemilk**
Since the turnaround time for our tests and the sometimes flaky reproducibility of failures was driving me nuts I've setup a parallel infrastructure using drone.io. The drone agents doing the actual stuff run on our own hardware, as does the coordinator. There are no time limits. It's container native. However this mandated a couple of changes/improvements to our setup:
 - Tests are no longer run as root inside the image. 
 - The first step after cloning dune-gdt is building a docker image with the code added. This is then used to run the test suite entirely in the container. The source is no longer mounted into a container. 
 - This leads to a fixed, immutable container, tagged with the commit hash, that can be re-run as is to examine errors. Currently this is only pushed to docker hub if either of the build stages failed.
 - I've changed travis setup to reflect this, but as I plan to retire using it altogether in the future if drone works out, the authoritative upload of the test container rests in drone.
 - Failure notices via email for the drone setup are sent from drone@pymor.org
 - There's currently no more testlog uploading. Which isn't much of a downside since we're not using those at all. I would still love to get data consolidation and time series analysis and whatnot from those somewhen though. 
 - Test binning is gone. It's got a huge overhead. See next point.
 - A complete test suite on drone took about 90 min walltime / 180 min CPU, with 2 parallel builds for gcc/clang. Compare this to 200 min walltime / 750 min CPU on travis (24 builders for the cpp stage, of which 2-6 run in parallel).

### CODE REVIEW

**Comment by renemilk** [comment]
Also, this has none of the gitlabci problems with docker in docker. Which is why I've already replaced the testing image building in xt-super with a drone setup too. 
Once this PR is green and merged the travis errors should fix themselves for @tobiasleibner too.

**Comment by renemilk** [comment]
OTOH this probably won't be get to be green due to the unrelated errors that popped up in master _after_ the last PR got merged. So I'll probably force the merge w/o the checks green once I'm happy that we're only getting errors that are already in master.

**Comment by tobiasleibner** [comment]
Very nice! Yeah, just merge, the errors in master were my fault due to a change in dune-xt-la. These errors should be fixed in dune-xt-la now, so maybe this PR will be green already. If not, I will fix the errors in #132.

**Comment by renemilk** [comment]
The described changes in how docker images are used for CI now also applies to all dune-xt modules (after the respective PRs are merged), @dune-community/dune-xt-devs

**Comment by renemilk** [comment]
blocked by https://github.com/dune-community/dune-xt-common/pull/136

**Comment by renemilk** [comment]
@dune-community/dune-xt-devs I've added a couple of azure instances to the drone agent pool and reduced the per machine builder count to avoid the machine overloads and subsequent built timeouts from yesterday.

**Pull request merged**
