### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by renefritze**

### CODE REVIEW

**Comment by renefritze** [comment]
Is that clang failure expected, @dune-community/dune-gdt-devs ?
https://dev.azure.com/dune-community/dune-gdt/_build/results?buildId=176

**Comment by tobiasleibner** [comment]
Yes, probably. Should be fixed in #159, which is ready to merge once the tests are passing. All tests are passing locally already.

**Comment by renefritze** [comment]
I've rebased on #159 now

**Comment by tobiasleibner** [comment]
The gcc jobs seem to be stuck. Though I don't know how much memory is assigned to the machines, I would bet they are out of memory, 4 compilations at a time might be too much.

**Comment by renefritze** [comment]
The machines one build supposedly runs in are Standard_DS2_v2: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dsv2-series

The script executes ninja without limitation, which should make it detech 2 vCPU and basically do `-j2` then. How/where did you see the 4 parallel compiles?

**Comment by renefritze** [comment]
And I just learned that Gitlab actually also supports the remote include feature for pipeline definitions that  made the new config for the dune-xt and gdt here so easy.

**Comment by tobiasleibner** [comment]
Ninja defaults to ``cores+2`` parallel builds, so it should be 4 on these machines. I would expect 7 GiB of memory to be too little for that. The builds are continuing now, but they are really slow, clang is already finished compiling (took 40 minutes or less), ``gcc_unstable`` is at ``19/74`` after 1h10.

**Comment by renefritze** [comment]
Huh, TIL. Did not know the `+2` part. I'll see if I can easily transplant the azure setup to gitlab again. 
I should've considered how mem hungry gdt compiles were before >_>

**Comment by renefritze** [comment]
Closing in favor of #162

**Pull request closed without merging**
