### PR TITLE
Fix hyperbolic tests

### PR DESCRIPTION
**Pull request by tobiasleibner**

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Tests are green though at least some of the EOC are failing. @renemilk, could you have a look?

**Comment by renemilk** [comment]
Could you link me to a log please?

**Comment by tobiasleibner** [comment]
https://travis-ci.org/dune-community/dune-gdt/jobs/374003793 has two failing tests, but still succeeds.

**Comment by tobiasleibner** [comment]
Some of the tests are probably failing since before this pull request. 
@dune-community/dune-gdt-devs, could you have a look at the following logs?
https://travis-ci.org/dune-community/dune-gdt/jobs/379117163
https://travis-ci.org/dune-community/dune-gdt/jobs/379117165
https://travis-ci.org/dune-community/dune-gdt/jobs/379117166
https://travis-ci.org/dune-community/dune-gdt/jobs/379117168
https://travis-ci.org/dune-community/dune-gdt/jobs/379117170

**Comment by renemilk** [comment]
It's not immediately clear to me what's going on there, since everything that is MPI related does work in https://travis-ci.org/dune-community/dune-gdt/builds/374804640

**Comment by tobiasleibner** [comment]
The errors are already showing up in the Travis build you linked, they just did not make the test fail. That was due to a bug in the ``travis_wait_new.bash`` script (see https://github.com/wwu-numerik/scripts/commit/60cd896bf3f1eb99066563aa1a07113e5a791d47).

**Comment by renemilk** [comment]
I see, right. I really don't know then and won't have time to look into it until after my vacation/conference block is over mid-June.

**Comment by tobiasleibner** [comment]
Okay, I disabled some tests and adjusted some tolerances. I will open issues for each of these changes so we do not forget to fix them properly at some point.

**Pull request merged**
