### PR TITLE
[WIP] update to 2.6 core modules

### PR DESCRIPTION
**Pull request by tobiasleibner**
Depends on #140.

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Yes, that's right. No objections.

**Comment by ftalbrecht** [comment]
Ok, after rebasing on `new-master` this looks like trivial changes. Can we merge these right away (aka does this work with 2.5), or do they only work with 2.6?

**Comment by tobiasleibner** [comment]
At least the python changes require dune-common 2.6. Not sure about the GeometryTypes stuff, but I would rather merge new-master first. I we fix the CI problems over there, it shouldn't take too long until we can merge, locally the tests (at least those that are not disabled) are passing.

**Comment by tobiasleibner** [comment]
Now that the xt modules are on 2.6, closing this in favor of #140.

**Pull request closed without merging**
