### PR TITLE
Fix compilation with icc, fix tests with -fsanitize-address, several other changes

### PR DESCRIPTION
**Pull request by tobiasleibner**
This fixes warnings and errors with the Intel Compiler, some errors in the tests detected by -fsanitize-address, and also contains other changes. I already tried merging with #187, there aren't too many conflicts. Once this PR is merged I will rebase #187.

### CODE REVIEW

**Review by ftalbrecht — COMMENTED** [review]
I think I already dropped this in #187, did you include that branch?

**Comment by ftalbrecht** [comment]
> This fixes warnings and errors with the Intel Compiler, some errors in the tests detected by -fsanitize-address, and also contains other changes. I already tried merging with #187, there aren't too many conflicts. Once this PR is merged I will rebase #187.

When doing so, have a look at the matrix operator to be sure to catch the changes about the `assemble_` I did in #187.

**Comment by tobiasleibner** [comment]
> I think I already dropped this in #187, did you include that branch?
> 
> This should have been a comment about [f1557ff](https://github.com/dune-community/dune-gdt/commit/f1557ff39e06e2023488f073da49559036e98e5b).

No, I did not include #187, I would like to merge this one first, given that it might take a while until #187 and the corresponding branch in dune-xt are actually merged.

> > This fixes warnings and errors with the Intel Compiler, some errors in the tests detected by -fsanitize-address, and also contains other changes. I already tried merging with #187, there aren't too many conflicts. Once this PR is merged I will rebase #187.
> 
> When doing so, have a look at the matrix operator to be sure to catch the changes about the `assemble_` I did in #187.

Okay :+1:

**Comment by tobiasleibner** [comment]
The [python tests fail](https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-gdt/-/jobs/417214). Doesn't really make sense to fix them in this branch, as #187 will completely overhaul the bindings. So I will just disable the failing test and maybe reactivate it when merging with #187 (if the test is still there). Are you fine with that, @ftalbrecht?

**Comment by ftalbrecht** [comment]
On 2020-09-10 12:08, Tobias Leibner wrote:
> The [python tests fail](https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-gdt/-/jobs/417214). Doesn't really make sense to fix them in this branch, as #187 will completely overhaul the bindings. So I will just disable the failing test and maybe reactivate it when merging with #187 (if the test is still there). Are you fine with that, @ftalbrecht?
> 

Yes, go ahead!

**Pull request merged**
