### PR TITLE
Complete Travis testing refactor

### PR DESCRIPTION
**Pull request by renemilk**
1.  Testing is now carried out in docker containers
2. There's one docker image with the common apt packages and system wide setup
3. there's then one image per compiler per supermodule branch
4. these are updated on each supermodule push
5. the dune-gdt travis itself pulls the ```compiler_branch``` image where the fallback for branch is master
6. all test targets are distributed, including headerchecks, into a fixed number of builders according to offsite generated profiling data (```make refresh_test_timings```)
7. to make this less error prone ```.travis.yml``` is now autogenerated via python script and unconditionally updated when test timings are refreshed
8. If you add new tests you currently have to rerun the refresh command, else travis will not run them
9. the base image is not automatically updated atm and I see no reason to make it
10. clang continues to outperform gcc in compile+testime, but don't think we should care atm though as that would add a lot of complexity to the whole setup
11. The tests are _evenly_ distributed according to timings on my workstation, apparently that's vastly different from real travis performance and not just facto X slower overall

### CODE REVIEW

**Comment by renemilk** [comment]
9. the base image is not automatically updated atm and I see no reason to make it
10. clang continues to outperform gcc in compile+testime, but don't think we should care atm though as that would add a lot of complexity to the whole setup
11. The tests are _evenly_ distributed according to timings on my workstation, apparently that's vastly different from real travis performance and not just facto X slower overall

**Comment by renemilk** [comment]
I'll just trigger the refresh on each travis builder before doing anything else. That way, if the test list differs from what's pickled, we'll have all builders time out because they're building all the tests. If no @dune-community/dune-gdt-devs object I'll merge this tonight.

**Comment by ftalbrecht** [comment]
No objections at all, nice work! Maybe at some point we can come up with a way to measure actual times an travis in the different builders to get a more realistic decomposition of the builders, but this is not a show stopper imho.

**Comment by renemilk** [comment]
Problem was a ```-O2``` that was baked into the docker base image and overrode the default ```-O0``` in the config file. No idea what's with the clang format status though.

**Comment by ftalbrecht** [comment]
The clang format thing is very strange, indeed. Otherwise: very nice!

**Comment by renemilk** [comment]
The maximum time over all builders was 35 minutes btw. So we could still reduce the number of builders to 11-ish.

**Comment by renemilk** [comment]
Ongoing: https://travis-ci.org/dune-community/dune-gdt/builds/180343421

**Comment by renemilk** [comment]
works with 11. I'll keep it there for now

**Pull request merged**
