### PR TITLE
Improve finite elements

### PR DESCRIPTION
**Pull request by ftalbrecht**
This adds new local finite element families, the concept of global finite elements, proper global interpolations and finishes a first draft of adaptivity (seems to work reliably now).

### CODE REVIEW

**Comment by ftalbrecht** [comment]
This depends on

* https://github.com/dune-community/dune-xt-common/pull/171
* https://github.com/dune-community/dune-xt-la/pull/94
* https://github.com/dune-community/dune-xt-grid/pull/92
* https://github.com/dune-community/dune-xt-functions/pull/75

**Comment by ftalbrecht** [comment]
merge when ready

**Comment by ftalbrecht** [comment]
I merged the current master, in particular your changes for ector-valued CG spaces (thanks for that).

**Comment by tobiasleibner** [comment]
Should be in master now.

**Comment by tobiasleibner** [comment]
Actually, not yet in master, but I will open a new PR including these changes soon.

**Comment by ftalbrecht** [comment]
I would like to keep this pr open and possibly merge it independently of the FV stuff (and probably before)...

**Comment by tobiasleibner** [comment]
If there are no ojections, I will close this and delete the branch, in favor of #159.

**Comment by ftalbrecht** [comment]
no objections

**Pull request closed without merging**
