### PR TITLE
WIP: Remove momentmodels

### PR DESCRIPTION
**Pull request by tobiasleibner**
This removes the stuff related to kinetic equations and momentmodels, and the dependency on `dune-xt-data`.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Is `HAVE_SPE10_DATA` already something meaningful? Apart from that: looks good.

**Comment by tobiasleibner** [comment]
> Is `HAVE_SPE10_DATA` already something meaningful?

Yes, once [this MR](https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-xt/-/merge_requests/81/diffs#15f48fd366d7f45a8afedc1710b54505d5040a0c) in `dune-xt` is merged.

**Comment by tobiasleibner** [comment]
Shall I merge this already? Until the `dune-xt` MR is merged, the spe10 related stuff will be disabled, but apart from that, everything should work fine.

**Comment by ftalbrecht** [comment]
On 28.09.21 10:17, Tobias Leibner wrote:
> Shall I merge this already? Until the `dune-xt` MR is merged, the spe10 related stuff will be disabled, but apart from that, everything should work fine.

Go ahead!

**Pull request merged**
