### PR TITLE
Updates from parabolic-lrbms-2018

### PR DESCRIPTION
**Pull request by ftalbrecht**
I do not get the CI problems from the other prs locally, so these are my current changes made ready for master, including bindings rewrite...

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Here I am getting [errors in dune-xt-la saddlepointsolver](https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-gdt/-/jobs/182020), @tobiasleibner

**Comment by tobiasleibner** [comment]
This is due to a change in ``dune-xt-la``, just change
```diff
-     XT::LA::SaddlePointSolver<double> solver(A, B, B, C);
+     XT::LA::SaddlePointSolver<Vector, Matrix> solver(A, B, B, C);
```

**Comment by ftalbrecht** [comment]
The failures seem due to timeouts, clang even passes. So this branch is a good candidate to be merged to get rid of the python errors, @tobiasleibner.

**Comment by tobiasleibner** [comment]
This fixes the python errors (locally) for me, thanks! The weird CI error is still there, I will try to investigate where that one comes from.

**Pull request merged**
